apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: redisgeek
  labels:
    app: concourse-web
  namespace: default
spec:
  virtualhost:
    fqdn: concourse.redisgeek.com
  routes:
    - conditions:
        - prefix: /
      services:
        - name: concourse-web
          port: 8080