apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redisgeek
  namespace: default
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
    - host: concourse.redisgeek.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: concourse-web
                port:
                  number: 8080