name: Remote Dispatch Action Initiator

on:
  push:
    branches:
      - main

jobs:
  remote-dispatch:
    name: "Remote Dispatch"
    runs-on: ubuntu-latest
    steps:
      - name: Remote Dispatch
        run: |
          curl -X POST https://api.github.com/repos/dashaun-cloud/azure-dashaun-cloud/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "cloud-pipeline-helm-dispatch", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'